name: guitar-juggling
favicon: null
layout_spectrum: 0.12738903565332294
typography_spectrum: 0.8319198868703097
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#3C493F'
    - '#7E8D85'
    - '#B3BFB8'
    - '#F0F7F4'
    - '#A2E3C4'
  brandStrength: 0.35755442711524665
  lightness: 0.7462114188820124
  saturation: 0.0944915774744004
  rhythmicContrast: 0.7233671741560102
purpose: []
